In [1]:
import pandas as pd

In [17]:
path_X_test = '/mnt/d/TON_IoT_Dataset/complete/X_test.csv'
path_X_train = '/mnt/d/TON_IoT_Dataset/complete/X_train.csv'
path_orig_dataset = '/mnt/d/TON_IoT_Dataset/combined.csv'
path_output = '/mnt/d/TON_IoT_Dataset/complete/_X_test.csv'

In [18]:
orig_df = pd.read_csv(path_orig_dataset, usecols=['label', 'ts'])
test_df = pd.read_csv(path_X_test)

In [23]:
split_millisecs = 20
start_time = orig_df['ts'].min()
orig_df['time_group'] = (orig_df['ts'] - start_time) // split_millisecs
orig_df = orig_df.reset_index(drop=True).sort_values('time_group')

In [24]:
test_time_groups = test_df['time_group'].unique()
orig_df_filtered = orig_df[orig_df['time_group'].isin(test_time_groups)]
orig_df_filtered

                  ts  label  time_group
170373    1554340588      0        7111
170372    1554340588      0        7111
170353    1554340589      0        7111
170352    1554340582      0        7111
170351    1554340585      0        7111
...              ...    ...         ...
22338987  1556549153      0      117539
22338988  1556549153      0      117539
22339020  1556549155      0      117539
22338990  1556549155      0      117539
22338985  1556549154      0      117539

[4363247 rows x 3 columns]

In [25]:
print(len(orig_df_filtered), len(test_df))

4363247 4363247

In [26]:
test_df['attack'] = orig_df_filtered['label'].values
test_df

,src,dst,features,time_group,attack
3,192.168.1.190:43530,192.168.1.190:7878,"[0.029281475522012896, -0.02336984722574583, 0...",7111,0
6,127.0.0.1:42100,127.0.0.1:7878,"[0.029281475522012896, -0.02336984722574583, 0...",7111,0
5,192.168.1.152:1880,192.168.1.152:40688,"[0.029281475522012896, -0.02336984722574583, 0...",7111,0
4,fe80::a691:b1ff:fe1e:5790:135,fe80::20c:29ff:fed2:b002:136,"[0.029281475522012896, -0.023369392483522593, ...",7111,0
7,192.168.1.152:53972,192.168.1.152:10502,"[0.029281475522012896, -0.02336984722574583, 0...",7111,0
...,...,...,...,...,...
4363193,192.168.1.180:123,150.101.217.196:123,"[0.029281475522012896, -0.02336848299907612, 0...",117539,0
4363194,192.168.1.195:50005,192.168.1.1:41952,"[0.029281475522012896, -0.02336984722574583, 0...",117539,0
4363207,192.168.1.195:50005,192.168.1.1:41952,"[0.029281475522012896, -0.02336984722574583, 0...",117539,0
4363237,192.168.1.195:50004,192.168.1.1:41952,"[0.029281475522012896, -0.02336984722574583, 0...",117539,0
4363244,192.168.1.195:50003,192.168.1.1:41952,"[0.029281475522012896, -0.02336984722574583, 0...",117539,0